/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ls_musiceffector_MusicEffector */

#ifndef _Included_org_ls_musiceffector_MusicEffector
#define _Included_org_ls_musiceffector_MusicEffector
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_org_ls_musiceffector_MusicEffector_init(JNIEnv *env, jobject instance);

JNIEXPORT void JNICALL Java_org_ls_musiceffector_MusicEffector_destory(JNIEnv *env, jobject instance);



JNIEXPORT jboolean JNICALL Java_org_ls_musiceffector_MusicEffector_isBassboostEnable(JNIEnv *env, jobject instance);

JNIEXPORT void JNICALL Java_org_ls_musiceffector_MusicEffector_setBassboostEnable(JNIEnv *env, jobject instance, jboolean is_enable);

JNIEXPORT jboolean JNICALL Java_org_ls_musiceffector_MusicEffector_isStrengthSupported(JNIEnv *env, jobject instance);

JNIEXPORT jint JNICALL Java_org_ls_musiceffector_MusicEffector_getBassboostRoundedStrength(JNIEnv *env, jobject instance);

JNIEXPORT void JNICALL Java_org_ls_musiceffector_MusicEffector_setBassboostStrength(JNIEnv *env, jobject instance, jint strength);



#ifdef __cplusplus
}
#endif
#endif
