/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ls_musiceffector_MainActivity */

#ifndef _Included_org_ls_musiceffector_MainActivity
#define _Included_org_ls_musiceffector_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ls_musiceffector_MainActivity
 * Method:    haha
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_org_ls_musiceffector_MainActivity_playUriTest(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
